# Define the stages that jobs will be assigned to
stages:
  - build
  - code-quality
  - test
  - deploy

# Job to detect code smells in the codebase
code-smell-backend:
  stage: code-quality
  image: openjdk:11
  only:
    - dev  # Only run this job in the 'dev' branch
  script:
    - echo "Detecting code smells..."  # Output a message indicating the job is running
    - mkdir $CI_PROJECT_DIR/backend/paw-pals/smells
    - java -jar $CI_PROJECT_DIR/backend/paw-pals/.gitlab/DesigniteJava.jar -i $CI_PROJECT_DIR/backend/paw-pals/src/main/java/com/asdc/pawpals -o $CI_PROJECT_DIR/backend/paw-pals/smells
    - cd backend/paw-pals/smells
    - ls -a
  artifacts:
    paths:
      - $CI_PROJECT_DIR/backend/paw-pals/smells
  when: manual  # Require manual intervention to run this job
  tags:
    - ugrad  # Run this job on a runner with the 'ugrad' tag

# Lint job to check the source code for potential errors, style violations, and other issues
# code-lint-frontend: 
#   stage: code-quality
#   only:
#     - dev
#   script:
#     - cd $CI_PROJECT_DIR/frontend
#     - npm install eslint --save-dev
#     - npm run lint
#   tags:
#     - ugrad

# # Format to readability, consistency, debugging, and collaboration.
# code-format-frontend: 
#   stage: code-quality
#   only:
#     - dev
#   script:
#     - cd $CI_PROJECT_DIR/frontend
#     - npm install prettier --save-dev
#     - npm run format
#   tags:
#     - ugrad

# Job to build the backend code
build-backend:
  stage: build
  image: maven:3-jdk-17  # Use the maven:3-jdk-17 Docker image for this job
  only:
    - dev
  script:
    - cd backend/paw-pals/
    - mvn clean
  when: manual
  tags:
    - ugrad

# Job to build the frontend code
build-frontend:
  stage: build
  only:
    - dev
  script:
    - echo "Building frontend..."
    - cd frontend  # Change to the 'frontend' directory
    - npm install  # Install the required dependencies
    - npm run build  # Build the frontend code
  when: manual
  tags:
    - ugrad

# Job to test the backend code
test-backend:
  stage: test
  only:
    - dev
  script:
    - echo "Testing backend..."
    - cd backend/paw-pals
    - mvn clean
  tags:
    - ugrad

# Job to deploy the backend code
deploy-backend:
  stage: deploy
  only:
    - dev
  script:
    - echo "Deploying backend..."
  when: manual
  tags:
    - ugrad

# Job to deploy the frontend code
deploy-frontend:
  stage: deploy
  only:
    - dev
  script:
    - echo "Deploying frontend..."
  when: manual
  tags:
    - ugrad